default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chillin_with_stocks_development

test:
  <<: *default
  database: chillin_with_stocks_test

production:
  <<: *default
  database: chillin_with_stocks_production
  username: chillin_with_stocks
  password: <%= ENV['CHILLIN_WITH_STOCKS_DATABASE_PASSWORD'] %>
